language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: N6wz3vmf+g3IoQt6/AaMjDVNiDEhefubLg0T1Bib140LcPorO/aPkyjLo00Dkj0TrpO5wbDFTSWecaJF1Skq0YF8RsQgZYv+suXlSqDXysN7unepaIjKVP+ODER0gZt5/BpvAWCWQIEBr4BK9uCemIZhYQZ/qHKzeb0SpDuDqr/m1wJNES4M7mye3+cDTNYRBnGsLZERuOISojrRwebyX3JHecRmQa5eEAV+b6j1mvdrMJQLWtaPlw+f0ybrtfSaiiSA14G5EREeVNnkDAQa1TcnR/BUMhe+3IYuOks1ViJsLIZzSw5buuu2ylfIkW/1nG0RikJaLZtEahdAVf/hf1KIKMFVp2NUHQ4hcBEMWltExskpt8Sq1wm7Ofh8RFlBcYF9R+DgxCQSVoNWMScFxR/RUJ8F/H8KmGOo/corX8dk4iCUXzT1oe6VDZZQ0ZelzLwVJ31KwaveV1WIMiRAgi3phEBwOZcckl1+wLpbt9Ci5Me4Lgo6nXKcnllYzYVCLE/z7ssN4J8fj2kZ7pqxC1MYAl7pbri4FamYDAHBephTpEGDsWdUW1nuzxqPRpWS9OkwvdoKpeU4FDdmk6Nqltv6n7kSPNuBQEnvtoefwSMvVeToyxaR/epfDA1OHbUrCs64Pg4iyCVmWmoTkl3k5oa8jgIgZ9JZmX5lX7WA4dk=
  app: boiling-beyond-37206
  on:
    repo: Jollendi91/node-mongoose-blog-integration-tests
